package io.github.askmeagain.pullrequest.dto.gitlab.project;

import lombok.Data;

import java.util.ArrayList;
import java.util.Date;

@Data
public class GitlabProjectResponse {
  public int id;
  public Object description;
  public String name;
  public String name_with_namespace;
  public String path;
  public String path_with_namespace;
  public Date created_at;
  public String default_branch;
  public ArrayList<Object> tag_list;
  public ArrayList<Object> topics;
  public String ssh_url_to_repo;
  public String http_url_to_repo;
  public String web_url;
  public String readme_url;
  public Object avatar_url;
  public int forks_count;
  public int star_count;
  public Date last_activity_at;
  public Namespace namespace;
  public String container_registry_image_prefix;
  public Links _links;
  public boolean packages_enabled;
  public boolean empty_repo;
  public boolean archived;
  public String visibility;
  public boolean resolve_outdated_diff_discussions;
  public ContainerExpirationPolicy container_expiration_policy;
  public boolean issues_enabled;
  public boolean merge_requests_enabled;
  public boolean wiki_enabled;
  public boolean jobs_enabled;
  public boolean snippets_enabled;
  public boolean container_registry_enabled;
  public boolean service_desk_enabled;
  public String service_desk_address;
  public boolean can_create_merge_request_in;
  public String issues_access_level;
  public String repository_access_level;
  public String merge_requests_access_level;
  public String forking_access_level;
  public String wiki_access_level;
  public String builds_access_level;
  public String snippets_access_level;
  public String pages_access_level;
  public String operations_access_level;
  public String analytics_access_level;
  public String container_registry_access_level;
  public String security_and_compliance_access_level;
  public String releases_access_level;
  public Object emails_disabled;
  public boolean shared_runners_enabled;
  public boolean lfs_enabled;
  public int creator_id;
  public Object import_url;
  public String import_type;
  public String import_status;
  public Object import_error;
  public int open_issues_count;
  public String runners_token;
  public int ci_default_git_depth;
  public boolean ci_forward_deployment_enabled;
  public boolean ci_job_token_scope_enabled;
  public boolean ci_separated_caches;
  public boolean ci_opt_in_jwt;
  public boolean ci_allow_fork_pipelines_to_run_in_parent_project;
  public boolean public_jobs;
  public String build_git_strategy;
  public int build_timeout;
  public String auto_cancel_pending_pipelines;
  public String ci_config_path;
  public ArrayList<Object> shared_with_groups;
  public boolean only_allow_merge_if_pipeline_succeeds;
  public Object allow_merge_on_skipped_pipeline;
  public boolean restrict_user_defined_variables;
  public boolean request_access_enabled;
  public boolean only_allow_merge_if_all_discussions_are_resolved;
  public boolean remove_source_branch_after_merge;
  public boolean printing_merge_request_link_enabled;
  public String merge_method;
  public String squash_option;
  public boolean enforce_auth_checks_on_uploads;
  public Object suggestion_commit_message;
  public Object merge_commit_template;
  public Object squash_commit_template;
  public Object issue_branch_template;
  public boolean auto_devops_enabled;
  public String auto_devops_deploy_strategy;
  public boolean autoclose_referenced_issues;
  public boolean keep_latest_artifact;
  public Object runner_token_expiration_interval;
  public String external_authorization_classification_label;
  public boolean requirements_enabled;
  public String requirements_access_level;
  public boolean security_and_compliance_enabled;
  public ArrayList<Object> compliance_frameworks;
  public Permissions permissions;
}
